### ISSUE TITLE
A riff on the ledger book page.

### ISSUE THREAD

**Issue by frankjmattia** [anthonymidili/BizBooks#2]
What do you think of trying something like this?

![screen-shot-2016-03-10-at-1 33 00-pm](https://cloud.githubusercontent.com/assets/19900/13680130/3b8672ba-e6c5-11e5-9394-895bd6270600.jpg)

**Comment by anthonymidili** [comment]
Not an issue or problem with code or app. In the future please send any view suggestions to me by either email or other means. Thank you
